
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: minio
  labels:
    app: minio
spec:
  selector:
    matchLabels:
      app: minio
      component: server
  serviceName: minio
  replicas: 4
  template:
    metadata:
      labels:
        app: minio
        component: server
    spec:
      containers:
      - name: minio
        envFrom:
        - configMapRef:
            name: minio-config
        image: elek/minio
        args:
        - minio
        - server
        - http://minio-{0...3}.minio.default.svc.cluster.local/data
        ports:
        - containerPort: 9000
        volumeMounts:
        - name: data
          mountPath: /data
        - name: mount
          mountPath: /opt/smoketest
      volumes:
      - name: data
        emptyDir: {}
      - name: mount
        hostPath:
          path: /home/elek/projects/flokkr/incubator/minio/examples/simple/smoketest
